const urls = {
    getAllMakes: '/makes',
    getAllModels: '/models',
    insertMake: '/makes/insert',
    checkDuplicateMake: "/makes/checkDuplicate",
    checkDuplicateModel: "/models/checkDuplicate",
    insertModel: "/models/insert",
    getCategories: "/category",
    insertCategory: "/category/insert",
    checkDuplicateCategory: "/category/checkDuplicate",
    getAllItems: "/item",
    insertItem: "/item/insert",
    checkDuplicateItem: "/item/checkDuplicate",
    insertStock: "/stock/insert",
    getStockData: "/stock/stockDetails",
    updateStock: "/stock/update",
    updateMake: "/makes/update",
    deleteMake: "/makes/delete",
    updateCategory: "/category/update",
    deleteCategory: "/category/delete",
    updateModel: "/models/update",
    deleteModel: "/models/delete",
    updateItem: "/item/update",
    deleteItem: "/item/delete",
    deleteStock: "/stock/delete",
    stockDetailsByBarcode: "/stock/stockDetailsByBarcode",
    stockDetailsByPartNumber: "/stock/stockDetailsByPartNumber",
    stockDetailsByBarcodeBilling: "/stock/stockDetailsByBarcodeBilling",
    stockDetailsByPartNumberBilling: "/stock/stockDetailsByPartNumberBilling",
    insertBillDetails:"/bill/insert"
}

export default urls;