const express = require('express');
const router = express.Router();
const stockController = require('../controllers/stockController');

router.post('/insert', stockController.insertStock);
router.get('/stockDetails', stockController.getStockDetails);
router.put('/update', stockController.updateStockDetails);
router.delete('/delete', stockController.deleteStock);
router.get('/stockDetailsByBarcode', stockController.getStockDetailsByBarcode);
router.get('/stockDetailsByPartNumber', stockController.getStockDetailsByPartNumber);
router.get('/stockDetailsByBarcodeBilling', stockController.getStockDetailsByBarcodeForBilling);
router.get('/stockDetailsByPartNumberBilling', stockController.getStockDetailsByPartNumberForBilling);
router.get('/stockDetailsByMake', stockController.getStockDetailsByMake);
router.get('/stockDetailsByModel', stockController.getStockDetailsByModel);
router.get('/stockDetailsByItem', stockController.getStockDetailsByItem);
router.get('/stockDetailsBycategory', stockController.getStockDetailsByCategory);
router.get('/duplicateBarcode', stockController.getDuplicateBarcode);
router.get('/duplicatePartNumber', stockController.getDuplicatePartNumber);
router.get('/stockDetailsForExport', stockController.getStockDetailsForExport);
module.exports = router;
